version: "3"
services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.28
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=thisisatest
    command: meilisearch --env="development"
    volumes:
      - ./data/:/meili_data:delegated